"use strict";
let userName = prompt ("What\'s Your Name ?");
let much = prompt ("How much do you Like birds ?");
let pet = prompt ("What do you prefer parots, love birds or canaries ?" , "Parots, Love birds, Canaries");
let about = prompt ("How did you hear about us?" , "Social media, A freind");
alert ("My name is: "+ userName + ".I prefer "+ pet + " I heared about you by "+ about);
console.log(userName , typeof userName);
console.log(much , typeof much);
console.log(pet , typeof pet);
console.log(about , typeof about);